httpVersion: '1.1'
responseChunkSize: 4096
outputBuffering: 'append'
determineRouteBeforeAppMiddleware: false
displayErrorDetails: true
addContentLengthHeader: true
routerCacheFile: '/application/app/bootstrap/cache/routes.cache'
