httpVersion: '1.1'
responseChunkSize: 4096
outputBuffering: 'append'
determineRouteBeforeAppMiddleware: false
displayErrorDetails: true
addContentLengthHeader: true
routerCacheFile: '/opt/upmarlin-api/app/bootstrap/cache/routes.cache'
